In [13]:
import geopandas as gpd
import pandas as pd
import shapely
from shapely import unary_union

In [5]:
cd "C:\Users\Administrator\Desktop\srl\analysis"

C:\Users\Administrator\Desktop\srl\analysis

In [29]:
routes = gpd.read_file("current_buses.geojson").to_crs("EPSG:7855")
routes

,OBJECTID,Shape_Length,shape_id,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color,route_type_text,geometry
0,1,0.179489,14-200-aus-1.2.H,14-200-aus-1,None,200,Bulleen - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (320539.73 5812624.251, 320533.67 5..."
1,2,0.182500,14-200-aus-1.3.R,14-200-aus-1,None,200,Bulleen - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (332639.56 5818014.29, 332680.92 58..."
2,3,0.200276,14-207-aus-1.2.R,14-207-aus-1,None,207,Doncaster SC - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (334876.16 5816543.59, 334873.48 58..."
3,4,0.199790,14-207-aus-1.3.H,14-207-aus-1,None,207,Doncaster SC - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (320539.73 5812624.251, 320533.67 5..."
4,5,0.111130,14-270-aus-1.2.R,14-270-aus-1,None,270,Mitcham - Box Hill,3,FF8200,FFFFFF,Bus,"LINESTRING (340855.67 5812837.88, 340839.46 58..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2198,2641,0.158948,81-BM3-aus-1.7.R,81-BM3-aus-1,None,433,Maddingley - Darley,701,FF8200,FFFFFF,NaN,"LINESTRING (272159.05 5825643.64, 272139.78 58..."
2199,2642,0.112988,81-BM3-aus-1.8.H,81-BM3-aus-1,None,433,Maddingley - Darley,701,FF8200,FFFFFF,NaN,"LINESTRING (273224.61 5830402.59, 273211.55 58..."
2200,2643,0.085557,81-BM3-aus-1.9.H,81-BM3-aus-1,None,433,Maddingley - Darley,701,FF8200,FFFFFF,NaN,"LINESTRING (273224.61 5830402.59, 273211.55 58..."
2201,2644,0.092362,81-BM4-aus-1.2.R,81-BM4-aus-1,None,434,Bacchus Marsh Station - Telford Park,701,FF8200,FFFFFF,NaN,"LINESTRING (273918.31 5825796.111, 273912.89 5..."
2202,2645,0.065884,81-BM4-aus-1.3.H,81-BM4-aus-1,None,434,Bacchus Marsh Station - Telford Park,701,FF8200,FFFFFF,NaN,"LINESTRING (272540.52 5829548.23, 272521.3 582..."

In [27]:
routes = routes[routes['route_short_name'].isin(hqpt)]
routes

,OBJECTID,Shape_Length,shape_id,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color,route_type_text,geometry
0,1,0.179489,14-200-aus-1.2.H,14-200-aus-1,None,200,Bulleen - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (320539.73 5812624.251, 320533.67 5..."
1,2,0.182500,14-200-aus-1.3.R,14-200-aus-1,None,200,Bulleen - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (332639.56 5818014.29, 332680.92 58..."
2,3,0.200276,14-207-aus-1.2.R,14-207-aus-1,None,207,Doncaster SC - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (334876.16 5816543.59, 334873.48 58..."
3,4,0.199790,14-207-aus-1.3.H,14-207-aus-1,None,207,Doncaster SC - City (Queen St),3,FF8200,FFFFFF,Bus,"LINESTRING (320539.73 5812624.251, 320533.67 5..."
4,5,0.111130,14-270-aus-1.2.R,14-270-aus-1,None,270,Mitcham - Box Hill,3,FF8200,FFFFFF,Bus,"LINESTRING (340855.67 5812837.88, 340839.46 58..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2165,2378,0.077074,61-533-aus-1.4.H,61-533-aus-1,None,533,Craigieburn North - Craigieburn,3,FF8200,FFFFFF,Bus,"LINESTRING (318421.84 5836379.05, 318420.95 58..."
2166,2379,0.077880,61-533-aus-1.5.R,61-533-aus-1,None,533,Craigieburn North - Craigieburn,3,FF8200,FFFFFF,Bus,"LINESTRING (317287.85 5840050.4, 317322.25 584..."
2167,2380,0.050534,61-537-aus-1.2.R,61-537-aus-1,None,537,Craigieburn Central SC - Craigieburn Station,3,FF8200,FFFFFF,Bus,"LINESTRING (315951.15 5837545.63, 315902.07 58..."
2168,2381,0.050355,61-537-aus-1.3.H,61-537-aus-1,None,537,Craigieburn Central SC - Craigieburn Station,3,FF8200,FFFFFF,Bus,"LINESTRING (318421.84 5836379.05, 318420.95 58..."
2169,2382,0.050355,61-537-aus-1.5.H,61-537-aus-1,None,537,Craigieburn Central SC - Craigieburn Station,3,FF8200,FFFFFF,Bus,"LINESTRING (318421.84 5836379.05, 318420.95 58..."

In [22]:
# Load Data
routes = gpd.read_file("current_buses.geojson").to_crs("EPSG:7855")
sa1    = gpd.read_file("../../PT/srl/G01_VIC_GDA2020.gpkg", layer="G01_SA1_2021_VIC").to_crs("EPSG:7855")

In [23]:
#Scope: Melb
check_scope = pd.read_csv('SA1.csv')
check_scope['SA4_CODE_2026'] = check_scope['SA4_CODE_2026'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
check_scope = check_scope[check_scope['SA4_CODE_2026'].isin(['206', '207', '208', '209', '210', '211', '212', '213', '214'])]
sa1['SA1_CODE_2021'] = sa1['SA1_CODE_2021'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
check_scope['SA1_CODE_2026'] = check_scope['SA1_CODE_2026'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
sa1 = sa1[sa1['SA1_CODE_2021'].isin(check_scope['SA1_CODE_2026'])]
f'SA1.csv size = {sa1.size}'

C:\Users\Administrator\AppData\Local\Temp\ipykernel_5460\1196945109.py:2: DtypeWarning: Columns (0: SA1_CODE_2026, 1: SA2_CODE_2026, 2: SA3_CODE_2026, 3: SA4_CODE_2026, 4: STATE_CODE_2026) have mixed types. Specify dtype option on import or set low_memory=False.
  check_scope = pd.read_csv('SA1.csv')

'SA1.csv size = 965552'

In [ ]:
Total Population: 3,644,910
400m: 649,779 (17.8%)
800m: 901,222 (24.7%)

new network
Total Population: 3,644,910
400m: 2,106,401 (57.8%)
800m: 3,083,187 (84.6%)

In [25]:
hqpt = ['235', '241', '246', '402', '472', '703', '901', '903', '216', '220', '223', '234', '305', '552', '670', '900', '902', '906', '907', '908', '905', '732', '561', '604', '825', '828', '153', '154', '170', '180', '190', '192', '200', '207', '232', '250', '251', '270', '390', '405', '406', '408', '420', '451', '460', '465', '467', '471', '475', '477', '501', '505', '508', '517', '527', '528', '529', '533', '537', '540', '541', '546', '570', '582', '603', '605', '630', '767', '791', '798', '800', '831', '893', '897', '898', '140A', '510', '733', '567', '556', '432', '555']

In [28]:
sa1["sa1_area_m2"] = sa1.geometry.area
total_pop = sa1["Tot_P_P"].sum() #abs col sum
print(f"Total Population: {total_pop:,.0f}")
for distance_m in [400, 800]:
    buf = gpd.GeoDataFrame(geometry=[unary_union(routes.buffer(distance_m))], crs=routes.crs)
    c = gpd.overlay(sa1, buf, how="intersection")
    c["pop_allocated"] = c["Tot_P_P"] * (c.geometry.area / c["sa1_area_m2"])
    pop = c["pop_allocated"].sum()
    print(f"{distance_m}m: {pop:,.0f} ({pop/total_pop:.1%})")

Total Population: 3,644,910
400m: 1,527,328 (41.9%)
800m: 2,237,266 (61.4%)

In [ ]:
len(hqpt)

In [19]:
routes['length'] = routes.geometry.length / 1000
b1_roundtrip = routes[routes['corridor'] == 'B1']['length'].sum() * 2
b2_roundtrip = routes[routes['corridor'] == 'B2']['length'].sum() * 2
adam = 2284411.27 # total from Resource-Chart.ipynb (the one that creates charts for service lvl)
b2_weekly_roundtrips = adam / (b1_roundtrip * 2 + b2_roundtrip) # km required per 1 service of every route
b1_weekly_roundtrips = b2_weekly_roundtrips * 2
operating_hours_per_week = 7*18
print(f'B1 frequency: {60/(b1_weekly_roundtrips/operating_hours_per_week):.0f} min')
print(f'B2 frequency: {60/(b2_weekly_roundtrips/operating_hours_per_week):.0f} min')

B1 frequency: 10 min
B2 frequency: 20 min

In [20]:
b1_roundtrip

np.float64(941.1025148521552)

In [21]:
b2_roundtrip

np.float64(4290.501314846121)

In [ ]:
sa1["sa1_area_m2"] = sa1.geometry.area
total_pop = sa1["Tot_P_P"].sum()

results = []
for _, row in routes.iterrows():
    buf = gpd.GeoDataFrame(
        geometry=[row.geometry.buffer(0)],  # placeholder, overwritten below
        crs=routes.crs
    )
    entry = {"route": row["route"], "corridor": row["corridor"]}
    for dist in [400, 800]:
        buf = gpd.GeoDataFrame(geometry=[row.geometry.buffer(dist)], crs=routes.crs)
        c = gpd.overlay(sa1, buf, how="intersection")
        c["pop_allocated"] = c["Tot_P_P"] * (c.geometry.area / c["sa1_area_m2"])
        pop = c["pop_allocated"].sum()
        entry[f"pop_{dist}m"] = round(pop)
        entry[f"pct_{dist}m"] = pop / total_pop
    results.append(entry)

coverage = pd.DataFrame(results).sort_values("pop_800m", ascending=False)
coverage["pct_400m"] = coverage["pct_400m"].map("{:.1%}".format)
coverage["pct_800m"] = coverage["pct_800m"].map("{:.1%}".format)
coverage["pop_400m"] = coverage["pop_400m"].map("{:,}".format)
coverage["pop_800m"] = coverage["pop_800m"].map("{:,}".format)
coverage

In [ ]:
coverage_raw = pd.DataFrame(results)

routes = routes.merge(
    coverage_raw[["route", "corridor", "pop_400m", "pop_800m"]],
    on=["route", "corridor"],
    how="left"
)

routes

In [ ]:
routes['pop_400m_per_km'] = routes['pop_400m'] / routes['length']
routes['pop_800m_per_km'] = routes['pop_800m'] / routes['length']
routes = routes.sort_values(by='pop_800m_per_km', ascending=False).reset_index(drop=True)
routes.tail(10)

In [ ]:
routes